# Generated by Django 5.2.8 on 2025-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproduct',
            name='sale',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
