# Generated by Django 5.2.8 on 2025-11-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_variantproduct_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantproduct',
            name='sale',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
