# Generated by Django 5.2 on 2025-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_variantproduct_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantproduct',
            name='image_1',
            field=models.ImageField(upload_to='e_commerce/product_images/'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='e_commerce/product_images/'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='e_commerce/product_images/'),
        ),
        migrations.AlterField(
            model_name='variantproduct',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='e_commerce/product_images/'),
        ),
    ]
