# Generated by Django 5.2 on 2025-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_variantproduct_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
