# Generated by Django 5.2.8 on 2025-11-26 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('shipping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=255)),
                ('district', models.CharField(choices=[('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Salem', 'Salem'), ('Tirunelveli', 'Tirunelveli'), ('Erode', 'Erode'), ('Vellore', 'Vellore'), ('Thoothukudi', 'Thoothukudi'), ('Dindigul', 'Dindigul'), ('Thanjavur', 'Thanjavur'), ('Kancheepuram', 'Kancheepuram'), ('Virudhunagar', 'Virudhunagar'), ('Karur', 'Karur'), ('Krishnagiri', 'Krishnagiri'), ('Namakkal', 'Namakkal'), ('Ramanathapuram', 'Ramanathapuram'), ('Kanyakumari', 'Kanyakumari')], default='Chennai', max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('TS', 'Telangana')], default='TN', max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_fixed_price', models.BooleanField(default=False)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(max_length=100)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order')),
                ('variant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variantproduct')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, through='payment.OrderItem', to='core.variantproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.shippingaddress'),
        ),
    ]
