# Generated by Django 5.2 on 2025-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_razorpay_order_id_alter_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
