# Generated by Django 5.2 on 2025-11-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_orderitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='pending', max_length=10),
        ),
    ]
