# Generated by Django 5.2 on 2025-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_stitched',
            field=models.BooleanField(default=False),
        ),
    ]
